"use client";

import { ChangeEvent, DragEvent, useMemo, useState } from "react";
import { AlertTriangle, ArrowRight, BriefcaseBusiness, Check, FileSpreadsheet, Gauge, LoaderCircle, Newspaper, ShieldCheck, Sparkles, UploadCloud } from "lucide-react";
import { Cell, Pie, PieChart, ResponsiveContainer, Tooltip } from "recharts";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Table, TableBody, TableCell, TableHead, TableHeader, TableRow } from "@/components/ui/table";

type ParsedPosition = { ticker: string; quantity: number; netInvested: number };
type PortfolioResult = { asOf: string; totalValue: number; positions: Array<{ ticker: string; name: string; quantity: number; netInvested: number; latestPrice: number; priceDate: string; marketValue: number; oneYearReturn: number; volatility: number; weight: number }>; unavailable: Array<{ ticker: string; error: string }>; scenarios: Record<"worst" | "bear" | "base" | "bull" | "best", number>; portfolioVolatility: number; largestWeight: number; concentrationIndex: number; marketMood: string; strategy: { fit: string; explanation: string }; news: Array<{ ticker: string; title: string; url: string; publisher: string; publishedAt: string | null; sentiment: "positive" | "negative" | "neutral" }>; methodology: string };
const COLORS = ["#52e0c4", "#7ea6ff", "#f7c65b", "#be8cf5", "#ff8294", "#58b5d9", "#8ad17e", "#dd8b4f"];
const money = (value: number) => new Intl.NumberFormat("en-US", { style: "currency", currency: "USD", maximumFractionDigits: 0 }).format(value);
const pct = (value: number) => new Intl.NumberFormat("en-US", { style: "percent", minimumFractionDigits: 1, maximumFractionDigits: 1 }).format(value);

function parseCsv(text: string) {
  const rows: string[][] = []; let row: string[] = [], field = "", quoted = false;
  for (let i = 0; i < text.length; i++) { const char = text[i]; if (quoted) { if (char === '"' && text[i + 1] === '"') { field += '"'; i++; } else if (char === '"') quoted = false; else field += char; } else if (char === '"') quoted = true; else if (char === ",") { row.push(field); field = ""; } else if (char === "\n") { row.push(field.replace(/\r$/, "")); if (row.some(Boolean)) rows.push(row); row = []; field = ""; } else field += char; }
  row.push(field.replace(/\r$/, "")); if (row.some(Boolean)) rows.push(row); return rows;
}
const numberFrom = (value = "") => { const negative = /^\s*\(/.test(value); const parsed = Number(value.replace(/[^0-9.-]/g, "")); return Number.isFinite(parsed) ? parsed * (negative ? -1 : 1) : 0; };
function positionsFromCsv(text: string) {
  const rows = parseCsv(text); if (rows.length < 2) throw new Error("The CSV does not contain any portfolio rows.");
  const headers = rows[0].map((value) => value.trim().toLowerCase());
  const index = (...names: string[]) => headers.findIndex((header) => names.includes(header));
  const tickerIndex = index("instrument", "ticker", "symbol"); const quantityIndex = index("quantity", "shares", "share quantity");
  const actionIndex = index("trans code", "action", "type", "transaction type"); const amountIndex = index("amount", "net amount", "cost basis"); const priceIndex = index("price", "average price", "avg price");
  if (tickerIndex < 0 || quantityIndex < 0) throw new Error("I could not find ticker and quantity columns. Use Instrument/Ticker and Quantity/Shares.");
  const map = new Map<string, ParsedPosition>();
  rows.slice(1).forEach((values) => { const ticker = (values[tickerIndex] || "").trim().toUpperCase(); if (!/^[A-Z0-9.-]{1,12}$/.test(ticker)) return; const action = (values[actionIndex] || "position").trim().toLowerCase(); const rawQuantity = Math.abs(numberFrom(values[quantityIndex])); if (!rawQuantity) return; const sign = /sell|sold/.test(action) ? -1 : /buy|position|holding/.test(action) || actionIndex < 0 ? 1 : 0; if (!sign) return; const amount = Math.abs(numberFrom(values[amountIndex])) || rawQuantity * Math.abs(numberFrom(values[priceIndex])); const current = map.get(ticker) || { ticker, quantity: 0, netInvested: 0 }; current.quantity += sign * rawQuantity; current.netInvested += sign * amount; map.set(ticker, current); });
  const positions = [...map.values()].filter((item) => item.quantity > .0000001).sort((a, b) => b.netInvested - a.netInvested);
  if (!positions.length) throw new Error("No positive stock or ETF positions were found after buys and sells were combined.");
  return { positions, transactionExport: actionIndex >= 0, rowCount: rows.length - 1 };
}
function futureValue(current: number, monthly: number, years: number, annualRate: number) { const rate = Math.pow(Math.max(.01, 1 + annualRate), 1 / 12) - 1; const months = years * 12; const currentFuture = current * Math.pow(1 + rate, months); const additions = Math.abs(rate) < 1e-9 ? monthly * months : monthly * ((Math.pow(1 + rate, months) - 1) / rate); return Math.max(0, currentFuture + additions); }

export function PortfolioDashboard() {
  const [fileName, setFileName] = useState(""); const [parsed, setParsed] = useState<{ positions: ParsedPosition[]; transactionExport: boolean; rowCount: number } | null>(null);
  const [result, setResult] = useState<PortfolioResult | null>(null); const [error, setError] = useState(""); const [loading, setLoading] = useState(false); const [dragging, setDragging] = useState(false); const [years, setYears] = useState(3); const [monthly, setMonthly] = useState(500);
  const handleFile = async (file?: File) => { if (!file) return; setError(""); setResult(null); try { if (!file.name.toLowerCase().endsWith(".csv")) throw new Error("Please upload a CSV file."); const next = positionsFromCsv(await file.text()); setFileName(file.name); setParsed(next); setLoading(true); const response = await fetch("/api/portfolio", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ positions: next.positions }) }); const payload = await response.json() as PortfolioResult & { error?: string }; if (!response.ok) throw new Error(payload.error || "Portfolio analysis failed."); setResult(payload); } catch (cause) { setError(cause instanceof Error ? cause.message : "The file could not be read."); } finally { setLoading(false); } };
  const projected = useMemo(() => result ? Object.fromEntries(Object.entries(result.scenarios).map(([key, rate]) => [key, futureValue(result.totalValue, monthly, years, rate)])) as Record<string, number> : null, [result, monthly, years]);
  const drop = (event: DragEvent) => { event.preventDefault(); setDragging(false); void handleFile(event.dataTransfer.files[0]); };
  const concentration = result ? result.largestWeight >= .3 ? "High" : result.largestWeight >= .18 ? "Medium" : "Lower" : "—";
  return <section className="workspace portfolio-workspace">
    <div className="portfolio-hero"><div><span className="eyebrow"><Sparkles/> Your portfolio, explained simply</span><h1>Upload your CSV. Get the whole picture.</h1><p>See what you own, where your risk sits, what recent headlines say, and how several historical scenarios could affect your balance.</p></div><div className="privacy-note"><ShieldCheck/><div><strong>Your CSV stays private</strong><span>The raw file is read in your browser and is not stored.</span></div></div></div>
    <div className="simple-steps"><span className={parsed ? "done" : "active"}><i>{parsed ? <Check/> : "1"}</i> Upload CSV</span><ArrowRight/><span className={loading ? "active" : result ? "done" : ""}><i>{result ? <Check/> : "2"}</i> Check market data</span><ArrowRight/><span className={result ? "active" : ""}><i>3</i> Read your snapshot</span></div>
    <label className={`upload-card ${dragging ? "dragging" : ""}`} onDragOver={(e) => { e.preventDefault(); setDragging(true); }} onDragLeave={() => setDragging(false)} onDrop={drop}><input type="file" accept=".csv,text/csv" onChange={(event: ChangeEvent<HTMLInputElement>) => void handleFile(event.target.files?.[0])}/><span className="upload-icon">{loading ? <LoaderCircle className="spin"/> : <UploadCloud/>}</span><div><strong>{loading ? "Reading your portfolio and market data…" : fileName || "Drop your portfolio CSV here"}</strong><span>{parsed ? `${parsed.rowCount} rows · ${parsed.positions.length} positions found` : "Or click to choose a file. Robinhood-style transaction exports and basic holdings files are supported."}</span></div><Button type="button" variant="outline">Choose CSV</Button></label>
    {error && <div className="error-banner"><AlertTriangle/><div><strong>I couldn’t read that portfolio</strong><span>{error}</span></div></div>}
    {parsed?.transactionExport && <div className="plain-note"><FileSpreadsheet/><div><strong>This is a transaction-history file.</strong><span>The snapshot combines buys and sells inside the dates covered by the CSV. If you owned shares before the file starts, your actual brokerage balance may be higher.</span></div></div>}
    {result && projected && <>
      <section className="plain-summary"><div className="summary-icon"><BriefcaseBusiness/></div><div><span>Your snapshot</span><h2>{money(result.totalValue)} estimated market value</h2><p>Based on {result.positions.length} positions with available prices as of {new Date(`${result.asOf}T00:00:00`).toLocaleDateString()}.</p></div><div className="summary-facts"><div><span>Largest holding</span><strong>{result.positions[0]?.ticker} · {pct(result.largestWeight)}</strong></div><div><span>Concentration</span><strong>{concentration}</strong></div><div><span>Recent news tone</span><strong>{result.marketMood}</strong></div></div></section>
      <section className="explain-grid"><article className="panel allocation-card"><div className="panel-heading"><div><span>What you own</span><h2>Portfolio mix</h2><p>Bigger slices mean more of your money depends on that holding.</p></div></div><div className="allocation-body"><div className="donut"><ResponsiveContainer width="100%" height="100%"><PieChart><Pie data={result.positions.slice(0,8)} dataKey="marketValue" nameKey="ticker" innerRadius="62%" outerRadius="90%" paddingAngle={2}>{result.positions.slice(0,8).map((item,index)=><Cell key={item.ticker} fill={COLORS[index%COLORS.length]}/>)}</Pie><Tooltip formatter={(value)=>money(Number(value))} contentStyle={{background:"var(--popover)",border:"1px solid var(--border)",borderRadius:10}}/></PieChart></ResponsiveContainer><div><strong>{result.positions.length}</strong><span>holdings</span></div></div><div className="allocation-list">{result.positions.slice(0,6).map((item,index)=><div key={item.ticker}><i style={{background:COLORS[index%COLORS.length]}}/><strong>{item.ticker}</strong><span>{pct(item.weight)}</span></div>)}</div></div></article>
      <article className="panel strategy-card"><div className="strategy-top"><span className="summary-icon"><Gauge/></span><div><span>What may fit new money</span><h2>{result.strategy.fit}</h2></div></div><p>{result.strategy.explanation}</p><div className="strategy-compare"><div><strong>DCA</strong><span>Spreads entry timing and can feel steadier.</span></div><div><strong>Lump sum</strong><span>Gets money invested sooner and captures more time in the market.</span></div></div><small>This is a historical fit check, not a personal recommendation.</small></article></section>
      <section className="panel scenario-panel"><div className="panel-heading"><div><span>What could happen</span><h2>Historical scenario range</h2><p>Choose a time period and optional monthly addition. These are examples built from past rolling returns—not predictions.</p></div><div className="scenario-controls"><div><span>Years</span>{[1,3,5,10].map((value)=><button className={years===value?"active":""} key={value} onClick={()=>setYears(value)}>{value}</button>)}</div><label><span>Add each month</span><Input type="number" min="0" step="50" value={monthly} onChange={(e)=>setMonthly(Math.max(0,Number(e.target.value)))}/></label></div></div><div className="scenario-grid">{[{key:"worst",label:"Worst historical case",help:"Very weak past periods"},{key:"bear",label:"Bear case",help:"Below-average past periods"},{key:"base",label:"Base case",help:"Middle historical result"},{key:"bull",label:"Bull case",help:"Stronger past periods"},{key:"best",label:"Best historical case",help:"Very strong past periods"}].map((item)=><article key={item.key} className={`scenario ${item.key}`}><span>{item.label}</span><strong>{money(projected[item.key])}</strong><em>{pct(result.scenarios[item.key as keyof typeof result.scenarios])} yearly historical rate</em><p>{item.help}</p></article>)}</div><div className="scenario-explainer"><AlertTriangle/><p>Markets do not move in a straight line. A “base case” is simply the middle of the historical sample. Your actual result can fall outside every box shown here.</p></div></section>
      <section className="panel holdings-panel"><div className="panel-heading"><div><span>Your positions</span><h2>What each holding contributes</h2><p>Value uses the latest available closing price. “1-year move” shows price change, not dividends.</p></div></div><Table><TableHeader><TableRow><TableHead>Holding</TableHead><TableHead>Shares in file</TableHead><TableHead>Latest price</TableHead><TableHead>Estimated value</TableHead><TableHead>Portfolio share</TableHead><TableHead>1-year move</TableHead><TableHead>Price swing</TableHead></TableRow></TableHeader><TableBody>{result.positions.map((item)=><TableRow key={item.ticker}><TableCell><strong>{item.ticker}</strong><span className="cell-sub">{item.name}</span></TableCell><TableCell>{item.quantity.toFixed(4)}</TableCell><TableCell>{money(item.latestPrice)}</TableCell><TableCell>{money(item.marketValue)}</TableCell><TableCell>{pct(item.weight)}</TableCell><TableCell className={item.oneYearReturn>=0?"positive":"negative"}>{pct(item.oneYearReturn)}</TableCell><TableCell>{item.volatility>=.4?"High":item.volatility>=.25?"Medium":"Lower"}</TableCell></TableRow>)}</TableBody></Table></section>
      <section className="panel news-panel"><div className="panel-heading"><div><span>What the market is talking about</span><h2>Recent news tied to your largest holdings</h2><p>Headline tone is a quick keyword scan. Open the story before drawing a conclusion.</p></div><Newspaper/></div><div className="news-grid">{result.news.length?result.news.map((item)=><a key={item.url} href={item.url} target="_blank" rel="noreferrer"><div><span>{item.ticker}</span><em className={item.sentiment}>{item.sentiment}</em></div><strong>{item.title}</strong><small>{item.publisher}{item.publishedAt?` · ${new Date(item.publishedAt).toLocaleDateString()}`:""}</small></a>):<div className="empty-news">No recent provider headlines were available for these tickers.</div>}</div></section>
      <div className="method-note"><ShieldCheck/><p><strong>How this works:</strong> {result.methodology} For personal research and education only. It does not consider your income, taxes, debts, goals, or risk tolerance.</p></div>
    </>}
  </section>;
}
